### ISSUE TITLE
Current Conda tests only work for new users. 

### ISSUE THREAD

**Issue by wmobley** [In-For-Disaster-Analytics/LLMRepository-Docker#65]
## 🐛 Bug Report
Our current test 
> if [ ! -d "$WORK/miniconda3" ]; then
Tests a specific location to see if conda exists. But more advanced users may have already install conda. This leads to the Container breaking. 

See Below: 
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
...
```
+ echo Installing...
Installing...
+ mkdir -p /work/00576/yosuke/ls6/miniconda3
+ curl https://repo.anaconda.com/miniconda/Miniconda3-py311_23.10.0-1-Linux-x86_64.sh -o /work/00576/yosuke/ls6/miniconda3/miniconda.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 57  115M   57 65.8M    0     0  71.7M      0  0:00:01 --:--:--  0:00:01 71.6M
100  115M  100  115M    0     0  81.8M      0  0:00:01  0:00:01 --:--:-- 81.8M
+ bash /work/00576/yosuke/ls6/miniconda3/miniconda.sh -b -u -p /work/00576/yosuke/ls6/miniconda3
PREFIX=/work/00576/yosuke/ls6/miniconda3
Unpacking payload ...

  0%|          | 0/70 [00:00<?, ?it/s]
                                      
concurrent.futures.process._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 387, in wait_result_broken_or_wakeup
  File "multiprocessing/connection.py", line 256, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 562, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 609, in result_iterator
  File "concurrent/futures/_base.py", line 446, in result
  File "concurrent/futures/_base.py", line 391, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[2977838] Failed to execute script 'entry_point' due to unhandled exception!

```

**Comment by wmobley** [comment]
Existing users also have an issue with older versions of Conda they may have stable not having --yes as a command.
